### ISSUE TITLE
This version has an issue when there are errors thrown

### ISSUE THREAD

**Issue by TimeForAChange** [m0ppers/promise-any#1]
I already had a version of "any" that I made myself but I tried yours because it's shorter. However, I went back to my own version because yours has an issue when an error is thrown - it doesn't show it, instead I got an error from one of the failed promises that went into "any".

Here's my use case:

I have files named after their own SHA256 and I don't know which directory they are in. So I simply start the I/O operation (read or delete) on _all_ directories and use the one that succeeds.

But before returning the contents of the file I add a little check. If I have an error in that `then(...)` I will see a "file not found" error from one of the failed promises instead of the error I throw.

```javascript
/**
 * Promisified version of node.js readFile method
 * @param {string} file With the full path
 * @returns {Promise}
 */
const readFile = function (file) {
    return new Promise((/**Function*/ resolve, /**Function*/ reject) => {
        fs.readFile(file, {encoding: 'utf8'}, (/**Error*/ err, /**string*/ data) => {
            if (err) {
                reject(err);
            } else {
                resolve(data);
            }
        });
    });
};

/**
 * This function is for files stored as string. If it is used on files stored as stream
 * the hash sum verification will fail if the file is not UTF-8. All files stored as
 * string are UTF-8. Also, files stored from stream may be large and should probably
 * be read as stream.
 * @param {string} hash A filename which also is the SHA256 of the file
 * @returns {Promise}
 */
module.exports.getHash = function (hash) {
    // Try all directories - see if any one attempt succeeds. We fail only if we
    // can't find the file anywhere. STORAGE_DIR: object with key:directory pairs
    return any(Object.keys(STORAGE_DIR).map(type => {
        return readFile(
            path.join(STORAGE_DIR[type], hash)
        )
        .then(txt => {
            // Before returning the contents of the file verify its crypto-hash
            const verify = crypto
                .createHash('sha256')
                .update(txt, 'utf8')
                .digest('hex');

            if (hash !== verify) {
                throw new Error(`Crypto-hash verification of file stored as ${hash} failed, actual hash is ${verify}`);
            }

            return txt;
        });
    }));
};
```

It works fine with my much more explicit version of "any":

```javascript
const any = function (promises) {
    return new Promise((/**Function*/ resolve, /**Function*/ reject) => {
        let countDown = promises.length;

        promises.map(promise => {
            return promise
            .then(resolve)
            .catch(err => {
                countDown -= 1;
                if (countDown === 0) {
                    reject(err);
                }
            });
        });
    });
};
```

**Comment by m0ppers** [comment]
Hi....i am not yet 100% sure if i understood your problem correctly. I have some test code made up:

```
var test = function() {
    return any([
        Promise.reject('fail')
    ], [
        Promise.resolve('ok').then(
            function() { throw new Error('Throw'); }
      )
    ]);
}
```

Is this a minimal testcase for your problem? If so i don't really get the problem about it. None of the promises succeeded so it is returning one of the errors (the first). if you change the order of the promises you will get the "throw" error.

Your version however is simply returning the error of the last promise :S

As to your use case i think your promise setup is simply wrong :o 

wouldn't it make more sense to do an exists check wrapped in any() to first determine the correct location and then continue working on the correct location?

**Comment by TimeForAChange** [comment]
The test case is the code I gave. It works with my "any" and has the issue I described with yours. Your test case has none of the promises succeed, as you yourself pointed out.

> As to your use case i think your promise setup is simply wrong :

Why?

> wouldn't it make more sense to do an exists check wrapped in any() to first determine the correct location and then continue working on the correct location?

No. That's not how node.js works. [You can read node.js documentation](https://iojs.org/api/fs.html#fs_fs_exists_path_callback):

> fs.exists() is an anachronism and exists only for historical reasons. There should almost never be a reason to use it in your own code.

**Comment by TimeForAChange** [comment]
PS: I added the `readFile()` that I'm using as helper function to my code sample.

**Comment by m0ppers** [comment]
You are right about the exists. Still I think your promise setup is wrong.

any() has been implemented for a use case "i don't care which of the promises is returned. any of them is ok". You seem to not care about where the file is located BUT that the hash is ok.

So (as far as i understood) are doing multiple things in the any() and using exists() or readFile() is not the point. The point is mixing up two things in the any().

you are doing:

```
any(
  multiple times
    readfile
    AND
    checkhash
)
```

So any() will only succeed if all of the above is true and if none worked out than it is returning one of the errors. And that's working. Your any() implementation just returns the error of the last promise (which is the throw() only because by coincidence the last promise returned the existing file). Try adding another directory which will be added at the end of the map and you will also get the same error with your version.

And this would be how I think (!) it should be done (though i am not completely into your use case obviously):

```
any(
   multiple times
      readfile
)
.then(
   checkHash
)
```

So first check and read (that's where I would have done an exists() only - which is not idiomatic to node as you pointed out correctly) all possible files determining the existing one and then check the hash separately and NOT in the any() as well.

**Comment by TimeForAChange** [comment]
The point is that my version of "any" works and yours does not. You can argue all you want but it won't change that simple fact. As for your calling what I do "wrong" - well, you are entitled to your OPINION. What is a FACT is, however, that my version of "any" works and yours does not. "Mixing up two things" -- YES, I'm _programming_ and I do TWO things in one function. As I said you can have your _opinion_, for MY code this is the best solution. AND IT WORKS, when you use promises. It does NOT work with our version of "any".

Your analysis is frankly speaking, BULLSHIT:

> Your any() implementation just returns the error of the last promise (which is the throw() only because by coincidence the last promise returned the existing file). 

Can you read code? I DELIBERATELY LOOK FOR THE PROMISE THAT WORKS! It is NOT a "coincidence".

Useless conversation. Your stuff DOE SNOT WORK, period. And you can't even read code. I have no time for such bullshit.

**Comment by TimeForAChange** [comment]
It is PERFECTLY ACCEPTABLE to chain a then() on a promise and do what I do!!! Learn about promises, child.

**Comment by steinerj** [comment]
This might be a case of feeding the troll, but well...

@TimeForAChange 

This implementation of ".any()" doesn't care for the errors which caused the rejection. The error returned is chosen at random for all intents and purposes (in this case, it's the first error, but it really doesn't matter).
Another valid approach is to return a list of all errors thrown, which is used here: http://www.effectiveui.com/blog/2014/11/11/promise-any-a-missing-use-case/ 

Kris Kowal's approach in his .any() implementation is to simply throw a new generic error. This is probably intentional to prevent exactly the thing you are doing in your code, i.e. using the any function for specific error handling.

```javascript
       function onRejected() {
            pendingCount--;
            if (pendingCount === 0) {
                deferred.reject(new Error(
                    "Can't get fulfillment value from any promise, all " +
                    "promises were rejected."
                ));
            }
        }
```

As we can see, error handling varies wildly between .any() implementations. However, all implementations have in common that they are not geared towards specific error handling of the collated promises. Or, simply put, if you need to handle a specific rejection, don't use .any(). Which is exactly what @m0ppers suggests for your code with his pseudo-code example:

```
any(
   multiple times
      readfile
)
.then(
   checkHash
)
```

Using that approach you can handle errors thrown by checkHash explicitely. That way you don't rely on the details (or side-effects) of various any-implementations. I'd argue, that this would result in more robust code. If your code indeed relies on handling the "Crypto-hash verification"-error, I'd consider it brittle, because the order of elements in the array passed into the any function matters. That's the part which is "coincidental".
I'd claim, that you simply are not using .any() correctly, by expecting it to result in a specific rejection. Indeed with any (haha) other implementation of the any-function than your own, your approach would fail. So your version of any() is tailored to your odd usage of .any(). It doesn't mean that this implementation is not generic. Quite the opposite.

Given that you didn't even bother to provide a minimal test case (your example is full of noise and doesn't highlight the core issue), your little meltdown in the end is quite appalling. After @m0ppers provided some good critique of your code, you resorted to ad hominem attacks and shouting. I have therefore reported you.

Nightynight.

**Comment by TimeForAChange** [comment]
> I have therefore reported you.

LoL, how HORRIBLE! Am I going to Guantanamo now?

Why are you so childishly stupid? Yes, that DOES get me every time.

**Comment by TimeForAChange** [comment]
Yes, I think you are right. It's cleaner to append the `then()` after the `any()`. I changed my code.

**Comment by TimeForAChange** [comment]
However, after looking at it some more I continue to believe that my "any" is far clearer (to read) *and* that what I did was perfectly okay. It's slightly more logical to append the `.then()` but I see no reason why it should fail.

So in my "any" I only changed the variable name (your "pending" is better) and that I return a new error message tailored specifically for the "any".

```javascript
const anyPromise = function (promises) {
    return new Promise((/**Function*/ resolve, /**Function*/ reject) => {
        let pending = promises.length;
        promises.forEach(promise => {
            return promise
                .then(resolve)
                .catch(err => {
                    pending -= 1;
                    if (pending === 0) {
                        reject(new Error('Cannot get fulfillment value from any promise'));
                    }
                });
        });
    });
};
```

and

```javascript
module.exports.getHash = function (hash) {
    return anyPromise(Object.keys(STORAGE_DIR).map(type => {
        return readFile(
            path.join(STORAGE_DIR[type], hash)
        );
    }))
    .then(txt => {
        // Before returning the contents of the file verify its crypto-hash
        //....
        return txt;
    });
};
```

But even after accepting your suggestion, when the `then()` is with the `readFile()` there is nothing _technically_ wring with this so an any that doesn't work... doesn't work.
